"""09 — Tabloları derle (T1 master results) ve tables.md render et.

T1: tüm baseline'lar (B0–B3) + tüm ML layer×model×CV → birleşik metrik matrisi.
Kaynak: analysis/recomputed_aggregate_metrics.csv (exact, fidelity-doğrulanmış)
        + reports/cp25/02_baselines.csv (baseline'lar).

tables.md: mevcut T1–T4 + anahtar analiz çıktılarını markdown olarak render eder
(eksik dosyalara dayanıklı; süreç ilerledikçe yeniden koşulabilir).
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import repro_common as rc  # noqa: E402

CP25 = rc.PROJECT_ROOT / "reports" / "cp25"


def build_t1() -> pd.DataFrame:
    rec = pd.read_csv(rc.ANALYSIS_DIR / "recomputed_aggregate_metrics.csv")
    rec = rec.assign(source="recomputed (cp25 layers)")
    rec = rec[["crop", "cv", "layer", "model", "n", "r2", "rmse_kg_da",
               "mae_kg_da", "mape_pct", "bias_kg_da", "ss_vs_b0", "source"]]

    bl = pd.read_csv(CP25 / "02_baselines.csv")
    bl["crop"] = bl["crop"].replace({"aycicegi_yaglik": "aycicegi"})
    bl = bl.rename(columns={"skill_score_vs_B0": "ss_vs_b0"})
    bl["cv"] = "LOYO"
    bl["layer"] = "baseline"
    bl = bl[["crop", "cv", "layer", "model", "n", "r2", "rmse_kg_da",
             "mae_kg_da", "mape_pct", "bias_kg_da", "ss_vs_b0"]]
    bl["source"] = "reports/cp25/02_baselines.csv"

    t1 = pd.concat([bl, rec], ignore_index=True)
    order_cv = {"LOYO": 0, "LOILO": 1, "Spatiotemporal": 2}
    order_layer = {"baseline": 0, "A": 1, "B": 2, "C": 3}
    t1 = t1.sort_values(by=["crop", "cv", "layer", "model"],
                        key=lambda s: s.map({**order_cv, **order_layer}).fillna(s)
                        if s.name in ("cv", "layer") else s).reset_index(drop=True)
    t1.to_csv(rc.TABLES_DIR / "T1_master_results.csv", index=False)
    print(f"[save] T1_master_results.csv rows={len(t1)}", flush=True)
    return t1


def _md_table(df: pd.DataFrame, floatfmt=3) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |",
             "|" + "|".join(["---"] * len(cols)) + "|"]
    for _, r in df.iterrows():
        cells = []
        for c in cols:
            v = r[c]
            if isinstance(v, float):
                cells.append(f"{v:.{floatfmt}f}")
            else:
                cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def render_md(t1: pd.DataFrame) -> None:
    md = ["# Paper 1 — Rendered Tables", "",
          "> Auto-generated by `repro/09_tables.py`. All numbers traceable to "
          "`analysis/` artifacts (fidelity-verified vs published cp25 tables; max |Δ|=0.0).", ""]

    md += ["## T1 — Master results matrix (LOYO temporal champion in **bold** per crop)", ""]
    # Show LOYO slice compactly per crop
    for crop in ("bugday", "aycicegi"):
        md += [f"### {crop} — LOYO (temporal generalization)", ""]
        sl = t1[(t1.crop == crop) & (t1.cv == "LOYO")][
            ["layer", "model", "n", "r2", "rmse_kg_da", "mae_kg_da", "mape_pct",
             "bias_kg_da", "ss_vs_b0"]].copy()
        md += [_md_table(sl), ""]
    md += ["_Full matrix (all CV schemes) in `tables/T1_master_results.csv`._", ""]

    extras = [
        ("T2 — Ablation (matched-sample A→B→C)", "T2_ablation.csv"),
        ("T3 — Per-stage NDVI forecast skill (FLOV, placeholder EVR_01)", "T3_per_stage.csv"),
        ("T3b — Per-stage NDVI forecast skill (FLOV, REAL parcel)", "T3_per_stage_real.csv"),
        ("T4 — Permutation importance (top rows)", "T4_feature_importance.csv"),
    ]
    for title, fname in extras:
        p = rc.TABLES_DIR / fname
        if not p.exists():
            continue
        df = pd.read_csv(p)
        md += [f"## {title}", ""]
        if fname == "T4_feature_importance.csv":
            df = df[df["rank"] <= 5]
        md += [_md_table(df), ""]

    # analysis extras
    for title, fname, sub in [
        ("Generalization gap (paired, fixed=LOILO champion)", "generalization_gap.csv", None),
        ("Baseline superiority (LOYO, ML vs B0)", "baseline_superiority.csv", None),
        ("Bootstrap 95% CI — LOYO R² (headline)", "bootstrap_ci.csv", "loyo_r2"),
        ("Moran's I (residual spatial autocorrelation)", "morans_i.csv", None),
    ]:
        p = rc.ANALYSIS_DIR / fname
        if not p.exists():
            continue
        df = pd.read_csv(p)
        if sub == "loyo_r2":
            df = df[(df.cv == "LOYO") & (df.metric == "r2")][
                ["layer", "crop", "model", "method", "point", "ci_lo", "ci_hi"]]
        md += [f"## {title}", "", _md_table(df), ""]

    (rc.TABLES_DIR / "tables.md").write_text("\n".join(md), encoding="utf-8")
    print("[save] tables.md", flush=True)


def main():
    t1 = build_t1()
    render_md(t1)


if __name__ == "__main__":
    main()
